
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: calculab_backend
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
      - ./backend/staticfiles:/app/staticfiles
      - ./.env:/app/.env
    ports:
      - "8080:8080"
    environment:
      - DJANGO_SETTINGS_MODULE=backend_calculab.settings
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
