# Generated by Django 4.2.16 on 2025-01-16 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('material_input_checker', models.CharField(max_length=50)),
                ('input_function_checker', models.CharField(max_length=100)),
                ('output_material', models.CharField(max_length=50)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soal', to='levels.level')),
            ],
        ),
    ]
