# Generated by Django 4.2.16 on 2025-01-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soal',
            name='base_function',
            field=models.CharField(default='f(x)', max_length=10),
        ),
    ]
