# Generated by Django 4.2.16 on 2025-01-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_soal_base_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soal',
            name='input_function_checker',
            field=models.JSONField(),
        ),
    ]
